#!/bin/bash

enhancement_only=false #If true, only the stage upto enhacement is performed on the multi-channel audio.
dereverb=wpe            #Optional {wpe,nmf}. If blank, then it wont do dereverberation.
denoise=              #Optional {wiener, spec_sub}. If not specified, then it wont do denoising.
localize=gcc_phat      #If not specified 'gcc_phat' is default. Values: {gcc_phat, gcc_scot}. It 'beamformit' is type of beamforming used then it does 
                                                                                              # TDOA estimation uing Beamformit. Default: GCC-PHAT
                        
beamform=mvdr_ta     #If not specified 'mvdr_nn' is default. Values: {dsb, mvdr_ta, mvdr_nn, gev_ta, gev_nn, beamformit}. Default: mvdr_nn
diarize=xvector        ##If not specified 'xtdoa' is default. Values: {xvector, tdoa, xtdoa}. Default: xtdoa
model_dir=exp/chain_cleaned_librispeech/tdnn_1d_sp                #If not specified 'exp/chain_cleaned/tdnn_1d_sp'(Librispeech acoustic model) is the default model.
graph_dir=exp/chain_cleaned_librispeech/tdnn_1d_sp/graph_tgsmall          #If not specified 'exp/chain_cleaned/tdnn_1d_sp/graph'(Librispeech graph directory) is default.
single_channel_decode=false  # If true, it will decode only single-channel file specified as a input file. In this case, the 
                             # <input-file> should have complete filename 
seq=dr  # The sequence in in which single channel enhancement is done. {dr: denoise and dereverberation and rd: dereverberation and denoising }                                                     
#If you want to run decoding on TCS data then  using exp/nnet3_chain/tdnn_1d_sp as acoustic model dir and #If you want to run decoding on TCS data then use 'exp/nnet3_chain/tdnn_1d_sp' as acosutic model dir and 'exp/nnet3_chain/tdnn_1d_sp/graph' as the graph dir

##########Best performing configuration for ASR#####################

#dereverb=wpe        
#denoise=               
#localize=gcc_phat                            
#beamform=mvdr_nn     
#diarize=xtdoa    
     
    


